apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resnet-server
  template:
    metadata:
      labels:
        app: resnet-server
    spec:
      containers:
        - name: resnet-server
          image: 1zhann/ai-model-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "1"
              memory: "1G"
            limits:
              cpu: "1"
              memory: "1G"
---
apiVersion: v1
kind: Service
metadata:
  name: resnet-service
spec:
  selector:
    app: resnet-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: NodePort